# basic options
title: Website 
author: Harsh Gandhi
email: gandhyharsh@yahoo.com
description: A wonderful site
instagram_username: harsh_290
github_username: Harshgandhi29

# Build settings
markdown: kramdown
theme: minima
