# basic options
title: Welcome 
author: Harsh Gandhi
email: gandhyharsh@yahoo.com
linkedin_username: harsh-gandhi-a71244191
github_username: Harshgandhi29

# Build settings
markdown: kramdown
theme: minima


