# basic options
title: Website 
author: Harsh Gandhi
email: gandhyharsh@yahoo.com
description: Contact
linkedin_username: harshguns@yahoo.ca
github_username: Harshgandhi29

# Build settings
markdown: kramdown
theme: minima


