# basic options
title: Website 
author: Harsh Gandhi
email: gandhyharsh@yahoo.com
description: Contact
linkedin_username: Harsh Gandhi
github_username: Harshgandhi29

# Build settings
markdown: kramdown
theme: minima


