# basic options
title: Harsh Simplified 
author: Harsh Gandhi
email: harsh.gandhi@uwaterloo.ca
linkedin_username: harsh-gandhi
description: Contact
github_username: Harshgandhi29

# Build settings
markdown: kramdown
theme: minima


